.

diff --git a/upload-script b/upload-script
--- a/upload-script
+++ b/upload-script
@@ -55,7 +55,8 @@ fi
 AUTH_HEADER="Authorization: token ${GITHUB_TOKEN}"
 
 # Create the correct Upload URL.
-RELEASE_ID=$(jq --raw-output '.release.id' "$GITHUB_EVENT_PATH")
+RELEASE_ID=$(echo ${GITHUB_REF:10}) 
+#$(jq --raw-output '.release.id' "$GITHUB_EVENT_PATH")
 
 # For each matching file..
 for file in $*; do
@@ -79,48 +80,48 @@ for file in $*; do
 
     FILENAME=$(basename "${file}")
 
-    UPLOAD_URL="https://uploads.github.com/repos/${GITHUB_REPOSITORY}/releases/${RELEASE_ID}/assets?name=${FILENAME}"
-    echo "Upload URL is ${UPLOAD_URL}"
+#    UPLOAD_URL="https://uploads.github.com/repos/${GITHUB_REPOSITORY}/releases/${RELEASE_ID}/assets?name=${FILENAME}"
+#    echo "Upload URL is ${UPLOAD_URL}"
 
     # Generate a temporary file.
-    tmp=$(mktemp)
+#    tmp=$(mktemp)
 
     # Upload the artifact - capturing HTTP response-code in our output file.
-    response=$(curl \
-        -sSL \
-        -XPOST \
-        -H "${AUTH_HEADER}" \
-        --upload-file "${file}" \
-        --header "Content-Type:application/octet-stream" \
-        --write-out "%{http_code}" \
-        --output $tmp \
-        "${UPLOAD_URL}")
+#    response=$(curl \
+#        -sSL \
+#        -XPOST \
+#        -H "${AUTH_HEADER}" \
+#        --upload-file "${file}" \
+#        --header "Content-Type:application/octet-stream" \
+#        --write-out "%{http_code}" \
+#        --output $tmp \
+#        "${UPLOAD_URL}")
 
     # If the curl-command returned a non-zero response we must abort
-    if [ "$?" -ne 0 ]; then
-        echo "**********************************"
-        echo " curl command did not return zero."
-        echo " Aborting"
-        echo "**********************************"
-        cat $tmp
-        rm $tmp
-        exit 1
-    fi
+#    if [ "$?" -ne 0 ]; then
+#        echo "**********************************"
+#        echo " curl command did not return zero."
+#        echo " Aborting"
+#        echo "**********************************"
+#        cat $tmp
+#        rm $tmp
+#        exit 1
+#    fi
 
     # If upload is not successful, we must abort
-    if [ $response -ge 400 ]; then
-        echo "***************************"
-        echo " upload was not successful."
-        echo " Aborting"
-        echo " HTTP status is $response"
-        echo "**********************************"
-        cat $tmp
-        rm $tmp
-        exit 1
-    fi
+#    if [ $response -ge 400 ]; then
+#        echo "***************************"
+#        echo " upload was not successful."
+#        echo " Aborting"
+#        echo " HTTP status is $response"
+#        echo "**********************************"
+#        cat $tmp
+#        rm $tmp
+#        exit 1
+#    fi
 
     # Show pretty output, since we already have jq
-    cat $tmp | jq .
-    rm $tmp
+#    cat $tmp | jq .
+#    rm $tmp
 
 done
